name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1
      id: go

    - name: Set GOPATH
      run: echo "::set-env name=GOPATH::${{ github.workspace }}"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        export PATH="${{ github.workspace }}/bin:${PATH}"
        go get -v -t -d ./...

    - name: Build
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build ./src

    - name: Test
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go test -v ./src/tests/
      